version: 2

project_name: wolgo

before:
  hooks:
    - go mod verify

builds:
  - main: .
    binary: wolgo
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X github.com/lucidfrontier45/wolgo/cmd.Version={{.Version}}
      - -X github.com/lucidfrontier45/wolgo/cmd.Commit={{.Commit}}
      - -X github.com/lucidfrontier45/wolgo/cmd.Date={{.Date}}
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: darwin
        goarch: amd64
      - goos: windows
        goarch: arm64

archives:
  - formats: ["binary"]

checksum:
  name_template: "checksums.txt"

upx:
  - enabled: true
    compress: best
    lzma: true
    goos: [linux, windows, darwin]
    goarch: [amd64, arm64]

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"
      - "^merge:"

release:
  github:
    owner: lucidfrontier45
    name: wolgo
